### ISSUE TITLE
Noble Mentions: Use global modifier value over local modifier when global is more specific

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#12]
When you have a global modifier that 1) is more specific than a local modifier or 2) has more qualifiers associated with it than the local modifier, then use the value of the global modifier over the local modifier.

Ex. Breast, Right 2:00
Normal breast parenchyma -> This should produce a modifier of Breast(Right, 2:00) instead of just Breast

Ex. Axillary Lymph Node, Right
Lymph node hyperplasia -> This should produce a modifier of Axillary Lymph Node (Right) instead of just Lymph Node.

**Comment by tseytlin** [comment]
Implemented. The new method will replace the "local" modifier with "global" one 
IF:
  global is a more specific class
  global and local are the same class, but global modifier has more qualifiers, unless some of the qualifiers are different. Ex Left vs Right
