### ISSUE TITLE
NobleMentions: Compound anchors fail to trigger an annotation

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#14]
Compound anchors appear to be picked up by NM. However, no annotations (accepted or rejected) are created based on the compound anchor.

**Comment by tseytlin** [comment]
The issue was related to DomainOntology.isAnchor() method excluding compound anchors if they were matched directly by a coder instead of being construed

**Comment by tseytlin** [comment]
I need more info. Which domain ontology? Which compound anchor to expect?

**Comment by tseytlin** [comment]
Can't replicate, closing
