### ISSUE TITLE
NobleMentions: Anchor does not trigger creation of annotation

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#15]
Anchor of "Invasive ductal carcinoma" does not trigger any appropriate annotations (accepted or rejected) for an unknown reason.

**Comment by tseytlin** [comment]
I can't replicate

**Comment by tseytlin** [comment]
Check isAnchorOf and synonymy of Ductal_Breast_Carcinoma in pathDx ontology
