### ISSUE TITLE
NobleMentions: Lexical item with longer span not associated with anchor

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#16]
If a modifier has a lexical item with a longer span, it should be favored over a lexical item that has the shorter span.

Example: "No evidence of malignancy" -> Should produce annotation "no evidence of" and assigned DefiniteNegatedExistence to malignancy anchor instead of "evidence" producing a label of ProbableExistence to malignancy anchor.

**Comment by tseytlin** [comment]
Sentence parser strips NO in the beginning of the sentence because it thing it is a bullet point since it matches this regex
^(([A-Z0-9-\\)]{1,2}\\.?)?\\s+)\\w.*

**Comment by tseytlin** [comment]
Fixed SentenceProcessor by adding a regex ("^(([A-Z]?[0-9-\\)]{0,2}\\.?)?\\s+)\\w.*") that doesn't exclude NO
