### ISSUE TITLE
Complement of section types not being used correctly by NM

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#22]
In the ontology "family history of cancer" and "no family history of cancer" have the following axiom hasSection some (not ('GROSS DESCRIPTION' or 'NATURE OF SPECIMENS')). This is causes annotations that do not have a Section assigned to it to not appear in the Accepted annotations. We need to figure out how to best address this situation.

Ex. "FAMILY HISTORY: Significant for a paternal great aunt with breast cancer, a paternal grandmother with postmenopausal breast cancer, paternal grandfather with sarcoma.
There are multiple paternal relatives with hematologic malignancies including primarily multiple myeloma, a paternal uncle with prostate cancer, another paternal uncle with liver cancer."

**Comment by mecst76** [comment]
Report: pt11 rep1
Domain: nlpCancer
Issue: All of the family history cancers are being assigned to rejected annotations. The axiom on family history of cancer says hasSection some (not(GROSS DESCRIPTION or NATURE OF SPECIMENS)). It appears that the complement is not being processed correctly by NM.

**Comment by tseytlin** [comment]
The reason annotations failed was because of temporality and not section info
