### ISSUE TITLE
Numeric expressions should follow equivalence axioms stating units

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#25]
In cancer.owl, tumor size mention and implicit tumor size mention have numbers without units triggering an annotation. However, in the ontology the numeric modifiers “size in cm”, “size in mm”, “dimension in cm”, and “dimension in mm” all have units required (e.g. are part of the equivalence axioms).

**Comment by mecst76** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix numeric expressions without a unit are being assigned to numeric modifiers that require a unit.](https://trello.com/c/Zjx2LdpL/2-fix-numeric-expressions-without-a-unit-are-being-assigned-to-numeric-modifiers-that-require-a-unit)

**Comment by tseytlin** [comment]
The issue had to do with the fact that the temp instance I was creating to validate the axioms didn't clean up properly between multiple uses. Hence the units were left over from the previous evaluation and hence the instance passed the test
