### ISSUE TITLE
UMLS Ontologies

### ISSUE THREAD

**Issue by trivedigaurav** [dbmi-pitt/nobletools#31]
A support for UMLS ontologies would be very, very useful! 💯

**Comment by tseytlin** [comment]
Not sure what you mean. UMLS can be imported into NobleTools and in fact has a pre-built dictionary. UMLS is currently distributed in .nlm format which is simply a .zip file that contains .RRF files (with some files split up into several).  Once unzipped and with split up files merged, NobleTools can import UMLS

**Comment by trivedigaurav** [comment]
Oh okay. I assumed this because it shows this message when trying to import a few terminologies from BioPortal...

![screen shot 2017-04-04 at 11 40 19 am](https://cloud.githubusercontent.com/assets/377867/24665479/85089898-192b-11e7-9512-2d7ec98730d3.png)
