### ISSUE TITLE
NM: Doesn’t pick up number value when number spelled out in text

### ISSUE THREAD

**Issue by mecst76** [dbmi-pitt/nobletools#34]
Domain: Pitt/smoking.owl

Example text:
social history : 
notable for heavy alcohol use and history of heavy tobacco use , although he quit two years ago .

NM generates an annotation of "just quit smoking mention" but should generate an instance of "smoking stopped for 1 year or greater mention”.

**Comment by mecst76** [comment]
I removed the termination group (But_Group) from all of the temporality modifier classes. The instance duration >= 1 yr has a window size of 10 bidirectional. So, from the ontology, this text should generate “smoking stopped for 1 year or greater mention” unless there is an issue with the sentence parse.

**Comment by mecst76** [comment]
Another example:
social history : 
lived at nursing home for the past ten months .
he used to live with his wife and son in texas .
he **smoked** a pack and a half for **five years** .

**Comment by mecst76** [comment]
Another example:
habits : 
he has a greater than 100 pack year **smoking history and quit 9 to 10 years ago** .
he denied use of alcohol for 8 to 9 years .

**Comment by mecst76** [comment]
Another example:
social history : 
he has been a smoker for the last 50 years and he drinks alcohol occasionally , but stopped in 1987 .

**Comment by tseytlin** [comment]
So there were two issues, both fixed:
1) numbers spelled out as words, were indeed not picked up. They are now
2) I found a bug in the code that ignored custom window size. Hence in the example above, the stopped modifier was considered too far from the target mention, because the default windows size of 8 was used. This too has been fixed
